### PR TITLE
fix: added ipfs

### PR DESCRIPTION
**Pull request by isunaslabs**
Added a multisig wallet widget

### CODE REVIEW

**Comment by isunaslabs** [comment]
@wuminzhe this needs you to approve it. Please approve it on your end

**Comment by isunaslabs** [comment]
@1022ranji  if Aki is busy please help me approving this on your end. It needs at least one person to approve it

**Review by 1022ranji — APPROVED** [review]

**Comment by isunaslabs** [comment]
I can't still merge it
image

**Comment by isunaslabs** [comment]
Aki needs to approve it

**Review by aurexav — APPROVED** [review]

**Pull request merged**
