### PR TITLE
chore: migrate staking records to subql

### LINKED ISSUE #4: Remove Centralized API
use subql

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Comment by 1022ranji** [comment]
image
Missing prompts and default tick boxes, like this:
image

**Comment by 1022ranji** [comment]
Locked page is missing records of completed _release_ and completed _unlock earlier_
image

**Comment by 1022ranji** [comment]
Transaction record time is wrong
image

**Comment by 1022ranji** [comment]
正在unbonding中的，后面的按钮应该是 rebond； 已经完成unbonding时期的，应该后面有个手动让用户 release 的按钮。
image

**Comment by 1022ranji** [comment]
Pay attention to the capitalization of the button text
image

**Comment by hackfisher** [comment]
@JayJay1024 @1022ranji What's the progress?

**Comment by JayJay1024** [comment]
In the previous scheme, locked, bonded, and unbonding were regarded as records. But for example rebond, the original unbonding records will be chaotic, so discussed it with the product manager before and then think about how to display this information. Now @ZolaxZola  seems to have a new plan

**Comment by JayJay1024** [comment]
refer: #241

**Pull request closed without merging**
