### PR TITLE
feat: estimated fee tips

### LINKED ISSUE #318: Add reminder text of estimated fee cost before sign a transaction
- Transfer
- Bond
- Claim Reward
- Change Controller
- Change Reward Destination
- Lock extra
- Unbond
- Rebond
....
etc

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Comment by ZolaxZola** [comment]
Capitalized the first letter of` Estimated `（`Transferable` ,too）
Attention that the previous _transferrable_ is typo.

**Comment by JayJay1024** [comment]
> Capitalized the first letter of`Estimated`（`Transferable` ,too） Attention that the previous _transferrable_ is typo.

Resolved, `Transferable` in #322

**Comment by ZolaxZola** [comment]
image

Fee Tips of` Claim Reward` was supposed to be added

**Comment by JayJay1024** [comment]
> Fee Tips of` Claim Reward` was supposed to be added

No, this is just the account selector, don't put this `Fee Tips` here

**Comment by ZolaxZola** [comment]
I'm not quite sure if it's an issue:
when making a common transfer
- [x] The amount from Fee tips on Darwinia Apps is always higher than on Polkadot apps 
- [ ] Fee amount from tips on Darwinia Apps seems to be the same while it always changes on Polkadot apps
image
image

**Comment by ZolaxZola** [comment]
image

**Comment by ZolaxZola** [comment]
> image

Got it from Jay：The Estimate Fee on Darwinia Apps = 1.1* （fee on Polkadot Fee）
In order to keep the same calculation as the transferrable.

**Comment by ZolaxZola** [comment]
> I'm not quite sure if it's an issue: when making a common transfer
> 
> * [x]  The amount from Fee tips on Darwinia Apps is always higher than on Polkadot apps
> * [ ]  Fee amount from tips on Darwinia Apps seems to be the same while it always changes on Polkadot apps
> 
> image
> 
> image

Can't reproduce this issue now(on polkadot apps fee changes while on Darwinia not). Let's work it out next time we meet this.

**Review by ZolaxZola — APPROVED** [review]

**Pull request merged**
