### PR TITLE
fix: unlock earlier action use controller account as signer

### LINKED ISSUE #262: use Controller Account to sign <unlock earlier>
Now we're using the current account to sign `unlock earlier`, which will fail when the current account is the stash account but not the controller account
https://darwinia.subscan.io/extrinsic/9224168-1

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Review by ZolaxZola — CHANGES_REQUESTED** [review]
image
when switching accounts, the current account area becomes blank in the selector

**Comment by JayJay1024** [comment]
> image when switching accounts, the current account area becomes blank in the selector

this has been fixed in #258

**Review by ZolaxZola — APPROVED** [review]

**Review by ZolaxZola — CHANGES_REQUESTED** [review]
https://crab.subscan.io/extrinsic/0x6117713c987b6443ba1f81332e6ed296bb4371c72be552ff2bbe5fdc2fc4c004
image
image

it seems that i unlock earlier successfully , but the lock record stay the same , the staking data also.  The Controller account do not have enough KTON to pay the `Total Fines`, and there is no reminder here.

**Review by sxlwar — APPROVED** [review]

**Review by sxlwar — DISMISSED** [review]

**Review by sxlwar — DISMISSED** [review]

**Comment by sxlwar** [comment]
conflicted @JayJay1024

**Review by sxlwar — DISMISSED** [review]

**Review by ZolaxZola — APPROVED** [review]

**Pull request merged**
