### PR TITLE
feat: deposits migration

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Comment by 1022ranji** [comment]
image
This function is normal, but the problem of UI display.

**Comment by 1022ranji** [comment]
image

**Comment by 1022ranji** [comment]
After I select the crab network, the prompt under the Darwinia network is still displayed.
image

**Comment by 1022ranji** [comment]
image
This function is only applicable to the Darwinia network, is it possible to remove this function on the crab network instead of disabling it?

**Review by sxlwar — APPROVED** [review]

**Pull request merged**
